#ifndef _CONFIG_H_
#define _CONFIG_H_

#include <Arduino.h>

// GLOBAL
#define BAUD_RATE 115200

enum DIRECTION {
    FORWARD,
    BACKWARD,
    LEFT,
    RIGHT,
    MOMENT_LEFT,
    MOMENT_RIGHT,
    UP,
    DOWN,
    STOP
};

// ROV
#define SENSOR_COUNT 2

// DEBUG FOR PRINTING
#define DEBUG 1

enum SENSORS {
    PRESSURE,
    IMU,
};

// IMU SENSOR
#define IMU_SCL 21
#define IMU_SDA 22
#define IMU_ADDRESS 0x68

// PRESSURE SENSOR
#define PRESSURE_MCLK 13
#define PRESSURE_MISO 12
#define PRESSURE_MOSI 11
#define PRESSURE_SCLK 10
#define D1_SEQUENCE 0x0F40       // pressure measurement sequence
#define D2_SEQUENCE 0x0F20       // temperature measurement sequence
#define WORD1_SEQUENCE 0x1D50    // word1 sequence
#define WORD2_SEQUENCE 0x1D60    // word2 sequence
#define WORD3_SEQUENCE 0x1D90    // word3 sequence
#define WORD4_SEQUENCE 0x1DA0    // word4 sequence
#define RESET_SEQUENCE 0x155540  // reset sequence
#define CONVERSION_DELAY_MS 35
#define COMM_FREQUENCY 500000

// CURRENT SENSOR
#define VIN A1
#define VCC 5.0
#define CURRENT_SENSOR_COUNT 4
#define CURRENT_SENSOR_FRONT_LEFT_PIN A2
#define CURRENT_SENSOR_FRONT_RIGHT_PIN A3
#define CURRENT_SENSOR_BACK_LEFT_PIN A4
#define CURRENT_SENSOR_BACK_RIGHT_PIN A5

enum CURRENT_SENSORS {
    CURRENT_SENSOR_FRONT_LEFT,
    CURRENT_SENSOR_FRONT_RIGHT,
    CURRENT_SENSOR_BACK_LEFT,
    CURRENT_SENSOR_BACK_RIGHT,
};

// MOTOR
enum MOTOR_ORIENTATION {
    HOTIZONTAL_FRONT_LEFT,
    HOTIZONTAL_FRONT_RIGHT,
    HOTIZONTAL_BACK_LEFT,
    HOTIZONTAL_BACK_RIGHT,
    VERTICAL_FRONT,
    VERTICAL_BACK,
    VERTICAL_LEFT,
    VERTICAL_RIGHT
};

#define MOTOR_COUNT 8

#define HORIZONTAL_FRONT_LEFT_PIN 2
#define HORIZONTAL_FRONT_RIGHT_PIN 3
#define HORIZONTAL_BACK_LEFT_PIN 4
#define HORIZONTAL_BACK_RIGHT_PIN 5
#define VERTICAL_FRONT_PIN 6
#define VERTICAL_BACK_PIN 7
#define VERTICAL_LEFT_PIN 8
#define VERTICAL_RIGHT_PIN 9
#define STOP_SPEED 1500
#define MAX_INTERVAL 400

// ETHERNET
#define MAC_COUNT 6
#define IP_COUNT 4
#define DNS_COUNT 4
#define GATEWAY_COUNT 4
#define SUBNET_COUNT 4
#define ETHERNET_MAC_0 0xDE
#define ETHERNET_MAC_1 0xAD
#define ETHERNET_MAC_2 0xBE
#define ETHERNET_MAC_3 0xEF
#define ETHERNET_MAC_4 0xFE
#define ETHERNET_MAC_5 0xED
#define ETHERNET_IP_0 192
#define ETHERNET_IP_1 168
#define ETHERNET_IP_2 1
#define ETHERNET_IP_3 7
#define ETHERNET_CONSOLE_0 192
#define ETHERNET_CONSOLE_1 168
#define ETHERNET_CONSOLE_2 1
#define ETHERNET_CONSOLE_3 9
#define ETHERNET_PORT 80
#define FRAME_RECIEVED_SIZE 18
#define FRAME_SENT_SIZE 10

#endif