#ifndef _CONFIG_H_
#define _CONFIG_H_

#include <Arduino.h>

// GLOBAL
#define BAUD_RATE 115200

// SOFTWARE SERIAL
// SOFTWARE SERIAL
#define DEBUG_SOFTWARE_SERIAL 0
#define SENSORS_SOFTWARE_SERIAL_RX 9
#define SENSORS_SOFTWARE_SERIAL_TX 8
#define MOTORS_SOFTWARE_SERIAL_RX 7
#define MOTORS_SOFTWARE_SERIAL_TX 6
#define SOFTWARE_SERIAL_BAUD_RATE 115200
#define UART_FRAME_RECIEVED_SIZE 14
#define UART_FRAME_SENT_SIZE 14
#define SENSORS_FRAME_SIZE 3
#define MOTORS_FRAME_SIZE 6
#define RELIABLE_START_FRAME '('
#define RELIABLE_END_FRAME ')'

#endif