#ifndef _CONFIG_H_
#define _CONFIG_H_

#include <Arduino.h>

// GLOBAL
#define BAUD_RATE 115200

// SOFTWARE SERIAL
#define DEBUG_SOFTWARE_SERIAL 0
#define SENSORS_SOFTWARE_SERIAL_RX 9
#define SENSORS_SOFTWARE_SERIAL_TX 8
#define MOTORS_SOFTWARE_SERIAL_RX 7
#define MOTORS_SOFTWARE_SERIAL_TX 6
#define SOFTWARE_SERIAL_BAUD_RATE 115200
#define UART_FRAME_RECEIVED_SIZE 14
#define UART_FRAME_SENT_SIZE 14
#define SENSORS_FRAME_SIZE 3
#define MOTORS_FRAME_SIZE 6
#define RELIABLE_START_FRAME '('
#define RELIABLE_END_FRAME ')'

// MOTORS
enum DIRECTION {
  FORWARD,
  BACKWARD,
  LEFT,
  RIGHT,
  MOMENT_LEFT,
  MOMENT_RIGHT,
  UP,
  DOWN,
  STOP,
  GENERIC,
};

enum MOTOR_ORIENTATION {
  HORIZONTAL_FRONT_LEFT,
  HORIZONTAL_FRONT_RIGHT,
  HORIZONTAL_BACK_LEFT,
  HORIZONTAL_BACK_RIGHT,
  VERTICAL_FRONT,
  VERTICAL_BACK,
  MOTOR_COUNT,
};

#define MOTOR_COUNT MOTOR_ORIENTATION::MOTOR_COUNT

#define DEBUG_MOTION 0
#define SPEED_INDEX_START 1
#define EXPONENT_INDEX_START 17
#define EXPONENT_COUNT 2
#define EXPONENT_INITAL 2.0
#define DIRECTION_INDEX 33
#define HORIZONTAL_FRONT_LEFT_PIN 2
#define HORIZONTAL_FRONT_RIGHT_PIN 3
#define HORIZONTAL_BACK_LEFT_PIN 4
#define HORIZONTAL_BACK_RIGHT_PIN 5
#define VERTICAL_FRONT_PIN 6
#define VERTICAL_BACK_PIN 7
#define VERTICAL_LEFT_PIN 8
#define VERTICAL_RIGHT_PIN 9
#define STOP_SPEED 1500
#define MAX_SPEED 1850
#define MAX_INTERVAL 300

#endif